SPECIALTIES = ['Eye Surgeon' 'Pulmonologist / Lung Specialist' 'Ent Surgeon'
 'Orthopedic Surgeon' 'Pediatric Surgeon' 'General Surgeon' 'Sexologist'
 'Pediatrician' 'General Physician' 'Ent Specialist' 'Liver Specialist'
 'Dermatologist' 'Dentist' 'Gynecologist' 'Cardiologist' 'Eye Specialist'
 'Gastroenterologist' 'Psychiatrist' 'Cosmetic Surgeon' 'Neuro Surgeon'
 'Radiologist' 'Nutritionist' 'Nephrologist'
 'Plastic Surgeon, Cosmetic Surgeon' 'Ent Surgeon, Ent Specialist'
 'Cancer Specialist / Oncologist' 'Pediatrician, Pediatrician'
 'Pathologist' 'Cardiac Surgeon' 'Vascular Surgeon'
 'Cardiologist, Cardiologist' 'Endocrinologist' 'Neurologist'
 'Psychologist' 'Hematologist, Haemoncologist'
 'Pulmonologist / Lung Specialist, Lung Surgeon' 'Physiotherapist'
 'Gastroenterologist, General Physician, Internal Medicine Specialist'
 'Urologist' 'Plastic Surgeon' 'Vascular Surgeon, General Surgeon'
 'General Surgeon, Laparoscopic Surgeon' 'Audiologist'
 'Pediatric Cardiac Surgeon' 'Lung Surgeon' 'Internal Medicine Specialist'
 'General Physician, Cardiologist' 'Aesthetic Physician'
 'General Physician, Internal Medicine Specialist'
 'General Physician, Nephrologist' 'Urologist, Sexologist, Andrologist'
 'Eye Surgeon, Eye Specialist'
 'Psychologist, Rehabilitation Medicine, Speech Therapist'
 'Interventional Cardiologist, Cardiologist, Interventional Cardiologist'
 'Gastroenterologist, General Physician' 'Physiotherapist, Chiropractor'
 'Dentist, Oral and Maxillofacial Surgeon'
 'Internal Medicine Specialist, General Physician, Family Medicine'
 'Gastroenterologist, Hepatologist' 'Homeopath'
 'Interventional Cardiologist'
 'General Surgeon, Laparoscopic Surgeon, Cancer Surgeon, Hepatologist'
 'Bariatric / Weight Loss Surgeon, General Surgeon, Laparoscopic Surgeon'
 'Ent Specialist, Ent Surgeon'
 'Endourologist, Sexologist, Urologist, Endourologist'
 'Urologist, Sexologist, Urologist, Endourologist, Andrologist'
 'Psychology' 'Pediatric Cardiologist'
 'Cardiologist, Cardiologist, Gastroenterologist, Diabetologist'
 'Urological Oncologist' 'Diabetologist, Internal Medicine Specialist'
 'Pediatric Oncologist and Hematologist']

CITIES = ['Lahore' 'Karachi' 'Rawalpindi' 'Mianwali' 'Multan' 'Islamabad'
 'Sargodha' 'Faisalabad' 'Mansehra' 'Rahim Yar Khan' 'Jhelum' 'Gujrat'
 'Hafizabad' 'Okara' 'Bahawalpur' 'Lodhran']


