[project]
name = "sehat-link"
version = "0.1.0"
description = "AI powered healthcare system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.0.2",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.1.1",
    "passlib>=1.7.4",
    "sqlmodel>=0.0.27",
    "psycopg2-binary>=2.9.11",
    "uvicorn[standard]>=0.38.0",
    "fastapi>=0.121.0",
    "supabase>=2.23.2",
]
